spring.datasource.url=jdbc:h2:mem:easyapplydb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.sql.init.mode=always
spring.h2.console.enabled=true

easyapply.match-threshold=0.70
